# Generated by Django 2.2 on 2020-02-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='dietary_fibre',
            field=models.FloatField(default=10, verbose_name='Dietary Fibre (mg)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='sodium',
            field=models.FloatField(verbose_name='Sodium (mg)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='sugar',
            field=models.FloatField(verbose_name='Sugar (g)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='total_carbohydrates',
            field=models.FloatField(verbose_name='Total_Carbohydrates (mg)'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_time',
            field=models.IntegerField(choices=[(1, 'Breakfast'), (2, 'Morning Snacks'), (3, 'Lunch'), (5, 'Dinner'), (4, 'Afternoon Snacks'), (6, 'Evening Snacks')], verbose_name='Meal Time'),
        ),
    ]
